### ISSUE TITLE
Make aoi in Source() more flexible

### ISSUE THREAD

**Issue by fwfichtner** [dlr-eoc/ukis-pysat#1]
aoi in Source() currently only accepts a geojson in WGS84. Make this more flexible to work with 1.) any CRS and 2.) files and bbox coordinates. Basically accept the same input as aoi in Image().

We could do something like this, but that would add `pyproj` as dependency:

```python
def prep_aoi(aoi, src_proj=None):
    """ Converts to Geojson Geometry and reprojects aoi to WGS84

    :param aoi: aoi
    :param src_proj: pyproj.proj.Proj, Source Projection, default: None
    :return: geojson.geometry.Polygon
    """
    if isinstance(aoi, geojson.geometry.Polygon):
        aoi = shape(aoi)

    if src_proj:
        project = pyproj.Transformer.from_proj(src_proj, pyproj.Proj(init='epsg:4326'))
        aoi = transform(project.transform, aoi)
    return geojson.dumps(aoi.__geo_interface__, sort_keys=True)
```

**Comment by MWieland** [comment]
Looks like a solid solution to me. The additional dependency to `pyproj` is not a problem from my point of view.

**Comment by MWieland** [comment]
We should also consider to simplify the [query()](https://github.com/dlr-eoc/ukis-pysat/blob/master/ukis_pysat/download.py#L68) method in this context. In particular, we should move the part related to metadata mapping for different sources into a central place. This could possibly be taken care of by the [_construct_metadata()](https://github.com/dlr-eoc/ukis-pysat/blob/master/ukis_pysat/download.py#L206)method.
