### ISSUE TITLE
Rename attribute "nodata" of the Image class

### ISSUE THREAD

**Issue by LisaKnopp** [dlr-eoc/ukis-pysat#105]
I just opended an image using ukis-pysat and wanted to work with its no data value. After some error messages I found out that the "nodata" attribute of the class Image does not represent the no data value of the underlying image, but the nodata value that shall be used when using the write-funtion. After having read the parameter description within the class definition this got clear. 

I could solve my problem easily by refering to dataset.nodata instead. However, I could imagine that the naming of the nodata attribute might be confusing for other users as well. Perhaps a renaming could be a solution?

**Comment by fwfichtner** [comment]
In most cases the nodata value is read from the scene, only when you are creating an `Image` starting from an `np.ndarray` `nodata` does anything.

I will update the documentation, changing the parameter name would break compatibility and `nodata` is still correct. Your solution is correct, just use the usual `rasterio` functionalities.
