### ISSUE TITLE
Replace EarthExplorer with SAT API

### ISSUE THREAD

**Issue by fwfichtner** [dlr-eoc/ukis-pysat#106]
Replace EarthExplorer with SAT API (https://landsatlook.usgs.gov/sat-api). First we need to check whether we can really find and get the same products there, this is not entirely clear to me on [first sight](https://www.usgs.gov/core-science-systems/nli/landsat/landsat-data-access?qt-science_support_page_related_con=0#qt-science_support_page_related_con).

This goes hand in hand with #103 and #104.

**Comment by fwfichtner** [comment]
In #120 we are changing to [Machine-to-Machine (M2M) API](https://m2m.cr.usgs.gov/). We still need to go through the Landsat [Data Access Site](https://www.usgs.gov/core-science-systems/nli/landsat/landsat-data-access?qt-science_support_page_related_con=0#qt-science_support_page_related_con) to have a clear view on what is best for us to use here. At the beginning the change in #120 and https://github.com/dlr-eoc/ukis-pysat/issues/104#issuecomment-802913849 seem logical to me.

**Comment by fwfichtner** [comment]
Also [pylandsat](https://github.com/yannforget/pylandsat/tree/master/pylandsat) is quite a heavy library and we only use it for its string formatting. If SAT API is not our way forward we could consider reproducing this part only.

**Comment by shiwakotisurendra** [comment]
with sat-api , we can get the collections but cannot search the STAC items.

**Comment by fwfichtner** [comment]
Like discussed, let's stick with `M2M` then for now and try to remove the dependency to pylandsat (which we only use to create the GCS keys).

**Comment by shiwakotisurendra** [comment]
So, after some more checks , sendpoint(https://landsatlook.usgs.gov/sat-api/stac/)  can be used for accessing STAC items from the sat-api.

**Comment by shiwakotisurendra** [comment]
we can access the collections and items of landsat image from [this_endpoint](https://landsatlook.usgs.gov/sat-api/stac/) , but i am getting error while trying to view using rasterio.
```python 
RasterioIOError: '/vsicurl/https://landsatlook.usgs.gov/data/collection02/level-1/standard/etm/2021/148/046/LE07_L1TP_148046_20210525_20210525_02_RT/LE07_L1TP_148046_20210525_20210525_02_RT_B2.TIF' not recognized as a supported file format.
```

**Comment by shiwakotisurendra** [comment]
I found something odd while querying items from [sat-api](https://landsatlook.usgs.gov/sat-api/stac/) . Please check this [notebook](https://gitlab.dlr.de/shiw_su/my-notebooks/-/blob/master/landsatlook.ipynb).

**Comment by MWieland** [comment]
Hi Surendra. Many thanks for looking into this. Could you just provide me access to the referenced notebook for cross-checking?

**Comment by MWieland** [comment]
My first guess would be that this relates to an authentication problem.
