### ISSUE TITLE
Update to STAC 1.0.0

### ISSUE THREAD

**Issue by fwfichtner** [dlr-eoc/ukis-pysat#112]
More information in this blogpost: https://medium.com/radiant-earth-insights/spatiotemporal-asset-catalog-stac-1-0-0-rc-1-released-59e7946b3873

**Comment by fwfichtner** [comment]
[v1.0.0-rc.2](https://github.com/radiantearth/stac-spec/releases/tag/v1.0.0-rc.2) is here.

**Comment by fwfichtner** [comment]
It has officially been released: https://medium.com/radiant-earth-insights/stac-specification-1-0-0-released-c59e8c848077

**Comment by fwfichtner** [comment]
@shiwakotisurendra do we need to do anything here? If not just close.

**Comment by fwfichtner** [comment]
Or even better, update to pystac 1.0.0 once it is released. I also prefer their new way of handling `StacIO`, maybe that's something we should do as well -> https://pystac.readthedocs.io/en/latest/api.html#pystac.StacIO.

**Comment by mwip** [comment]
I think I found something that might be linked to this: 

Following the example in the Readme, I find that `AttributeError: 'Catalog' object has no attribute 'to_pandas'`
```
...
# inspect MetadataCollection with Pandas
cat_df = cat.to_pandas()
...
```

**Comment by shiwakotisurendra** [comment]
Sorry for the inconvenience , in fact readme is not uptodate anymore.

**Comment by fwfichtner** [comment]
@shiwakotisurendra please update to pystac 1.0.0.
