### ISSUE TITLE
Build array subset from window tiles

### ISSUE THREAD

**Issue by BoehnkeC** [dlr-eoc/ukis-pysat#12]
Provide a method to build an array subset from window tiles.
The current workflow is to call the subset window in a for-loop through the [get_tiles](https://github.com/dlr-eoc/ukis-pysat/blob/master/ukis_pysat/data.py#L280) method. Subsetting the array is currently performed by the user by indexing the array with the window properties:
```
for window in data.Image(img_path).get_tiles():
    (row_start, row_stop), (col_start, col_stop) = window_tile.toranges()
    array[0][row_start: row_stop, col_start: col_stop]
```

This can be outsourced to a new method in [ukis_pysat.data](https://github.com/dlr-eoc/ukis-pysat/blob/master/ukis_pysat/data.py):
```
def get_subset(self, window_tile, array, band=0):
    (row_start, row_stop), (col_start, col_stop) = window_tile.toranges()
    return array[band][row_start: row_stop, col_start: col_stop]
```

Performance decreases when requesting the image array for each call:
```
def get_subset(self, window_tile, band=0):
    (row_start, row_stop), (col_start, col_stop) = window_tile.toranges()
    return self.arr[band][row_start: row_stop, col_start: col_stop]
```

This can be solved by handing the array to the new method directly. However, this requires refactoring the [constructor ](https://github.com/dlr-eoc/ukis-pysat/blob/master/ukis_pysat/data.py#L23) of the Image class so that arrays are accepted without handing a dataset as it is currently done [here](https://github.com/dlr-eoc/ukis-pysat/blob/master/ukis_pysat/data.py#L31).

Possible solution:
```
if isinstance(dataset, rasterio.io.DatasetReader) and isinstance(arr, np.ndarray):
    self.dataset = dataset
    self.arr = arr
elif isinstance(arr, np.ndarray):
    self.arr = arr
```

**Comment by fwfichtner** [comment]
I'm not sure where you're heading. You can use the windows (=tiles) for [reading and writing](https://rasterio.readthedocs.io/en/latest/topics/windowed-rw.html).

If you need the array you could do something like that:
```python
for tile in img.get_tiles():
    transform = windows.transform(tile, ds.transform)  # in case you need the window transform
    return self.arr[tile.toslices()]
```
