### ISSUE TITLE
Thoughts about a metadata object

### ISSUE THREAD

**Issue by MWieland** [dlr-eoc/ukis-pysat#13]
Currently we create, harmonize and store metadata in geojson for each source directly in [construct_metadata ](https://github.com/dlr-eoc/ukis-pysat/blob/master/ukis_pysat/download.py#L161) method. This works fine at the moment, but is errorprone in case we may want to expand the metadata attributes, add further sources or modify existing metadata at some stage. Therefore, it would be good to have a dedicated metadata object with clearly defined attributes, dtypes, constraints, validation routines and descriptions.

An interesting approach to solve this in a bit more flexible way than just using a dictionary could be [dataclasses ](https://docs.python.org/3/library/dataclasses.html). They have been added to the Python standard library since 3.7. This would restrict us to use only Python>=3.7. 

What are your thoughts on such a restriction and the possible gains from a dataclass?

**Comment by fwfichtner** [comment]
Dataclasses do also not really solve the problem. You could use [mixins](https://easyaspython.com/mixins-for-fun-and-profit-cb9962760556), so basically multiple inheritance.
 Something like:
```python
class OrbitMixin():
    orbitnumber = ...
```
This would enable us to check the metadata objects for features via `isinstance()`.

I'm not really familiar with mixins, but that's what @nmandery suggested and it sounds like it's worth a shot. It is definitley better than the current dictionairy approach. A normal class hierarchy might overcomplex things.
