### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by shiwakotisurendra** [dlr-eoc/ukis-pysat#146]
I think I found something that might be linked to this: 

Following the example in the Readme, 
```
# inspect MetadataCollection with Pandas
cat_df = cat.to_pandas()
```
... I find that `AttributeError: 'Catalog' object has no attribute 'to_pandas'`

However, `Catalog` has a `.to_dict()` method, which indicates, I am using STAC version `1.0.0-beta.2`: 

`{'id': 'asdfasfasfasfasdf', 'stac_version': '1.0.0-beta.2', 'description': 'Creation Date: 2021-07-12 15:23:11.314274, Datahub: Scihub', 'links': [{'rel': 'root', 'href': None, 'type': 'application/json'}]}`

_Originally posted by @mwip in https://github.com/dlr-eoc/ukis-pysat/issues/112#issuecomment-878279337_

Readme is not upto date anymore ..after pystac is used in version 1.0.0

**Comment by mwip** [comment]
While we're at it the docs would also need an update: https://github.com/dlr-eoc/ukis-pysat/blob/master/docs/index.rst
