### ISSUE TITLE
Download Method Conflict in SCIHUB and EARTHEXPLORER

### ISSUE THREAD

**Issue by shiwakotisurendra** [dlr-eoc/ukis-pysat#151]
**Describe the bug**
when the item is created we set a value for the [ID's](https://github.com/dlr-eoc/ukis-pysat/blob/master/ukis_pysat/data.py#L394),

But when we query the hub we take another value of the item  ìtem.id for Landsat and ```item. Properties['uuid']  for sentinel to download.

**To Reproduce**
To download we can give the ```item.id``` (product "ID") [here ](https://github.com/dlr-eoc/ukis-pysat/blob/master/ukis_pysat/data.py#L448) always and  solve this internally.

**Expected behavior**
```UKIS_PYSAT``` download method for ```SCIHUB``` and ```EARTHEXPLORER``` both should have used  either```product_uuid``` or ``product_id"``` .

**Comment by fwfichtner** [comment]
please use the product id (`item.id`), that's more consistant.

**Comment by shiwakotisurendra** [comment]
but we are using [this](https://github.com/dlr-eoc/ukis-pysat/blob/master/ukis_pysat/data.py#L479) to download sentinel , which uses product_uuid .

**Comment by shiwakotisurendra** [comment]
But we are using [this](https://github.com/dlr-eoc/ukis-pysat/blob/master/ukis_pysat/data.py#L479) to download sentinel  , which links to ```sentinelsat.SentinelAPI``` and they are using ```product_uuid``` for download.

**Comment by fwfichtner** [comment]
You would need to go from `item.id` to `product_uuid`. Maybe you can also support both of them, that would be better for compatibility with older versions as well.
