### ISSUE TITLE
Split up package into subsets

### ISSUE THREAD

**Issue by fwfichtner** [dlr-eoc/ukis-pysat#16]
**Is your feature request related to a problem? Please describe.**
To use UKIS-pysat we always require GDAL and other heavy dependencies to be installed. That's not very handy for lightweight and small Docker images.

**Describe the solution you'd like**
Split up package into subsets like suggested [here](https://github.com/dlr-eoc/ukis-pysat/issues/9#issuecomment-625711290) so you can only install the functionalities you need:

```shell
pip install ukis-pysat  # would then only install ukis_pysat.file
```
```shell
pip install ukis-pysat[complete]  # would then install everything
```
```shell
pip install ukis-pysat[data]  # would then install ukis_pysat.file and ukis_pysat.data
```
```shell
pip install ukis-pysat[raster]  # would then install ukis_pysat.file and ukis_pysat.raster
```

**Additional context**
We need to carefully describe this in the Documentation, similar to what they have done [in dask](https://docs.dask.org/en/latest/install.html#pip).

**Comment by fwfichtner** [comment]
When https://github.com/yannforget/pylandsat/pull/1 goes through we would also get rid of pandas.

**Comment by fwfichtner** [comment]
@MWieland @BoehnkeC shall we publish another version after this it merged?

**Comment by MWieland** [comment]
I would say yes.

**Comment by BoehnkeC** [comment]
I also think that a new version is needed here.
