### ISSUE TITLE
Module names

### ISSUE THREAD

**Issue by MWieland** [dlr-eoc/ukis-pysat#18]
Not 100% happy with the naming of modules "data.py" and "downloads.py". Currently "data.py" deals with all the raster stuff and "downloads.py" deals more generally with data access and metadata queries. "downloads.py" is/will be more than downloading and "data.py" is more raster processing than data management. Personally I find this confusing and would suggest to rename the two modules as follows:

"downloads.py" -> "data.py"
"data.py" -> "raster.py"

What do you think about this?

**Comment by fwfichtner** [comment]
We could do this and should do it fast if we decide to do so as this will break all compatibility. I don't have a naming preference myself.
@BoehnkeC what do you think?

**Comment by BoehnkeC** [comment]
I agree to rename the scripts in the proposed way. To be honest, I had the same issues when drawing a semantic connection to the files.

**Comment by fwfichtner** [comment]
Calling it version 0.2.0 is wrong accordint to semver, but we are in such an early state that it should be okay.
