### ISSUE TITLE
Accept WKT string as AOI

### ISSUE THREAD

**Issue by BoehnkeC** [dlr-eoc/ukis-pysat#26]
Downloading data requires an area of interest. The AOI is either provided as a GEOJSON file or a bounding box tuple with lat lon coordinates (String, Tuple).

The [function ](https://github.com/dlr-eoc/ukis-pysat/blob/master/ukis_pysat/data.py#L311)`prep_aoi(aoi).wkt` performs thse steps:

- Read a GEOJSON file and convert the geometry parameter into a shapepy.geometry.shape object
- Parse a bounding box tuple into a shapely.box object

I find the choice between GEOJSON file and bounding box quite restricting. A bounding box does not resolve AOIs more complex than a quadrilateral. On the other hand, having a GEOSJON file requires I/O operation both from the user as well from the ukis-pysat side.

I suggest to also accept WKT strings as valid AOI inputs.

**Comment by BoehnkeC** [comment]
@MWieland, @fwfichtner, what do you think?

**Comment by fwfichtner** [comment]
That's fine.

**Comment by BoehnkeC** [comment]
Yes, I'll take care of it.

**Comment by MWieland** [comment]
Thats a great idea. We use fiona to open the dataset, which means that it should support out of the box all ogr drivers (including shapefile, KML or postgres). This still needs to be tested and documented, but should work as is. WKT should also be straight forward to support this way.

**Comment by MWieland** [comment]
Not sure about fiona and wkt reads, but you could simply do something like:
`shapely.wkt.loads(WKT_STRING)`
The actual CRS transform is done with shapely anyway.

**Comment by BoehnkeC** [comment]
That is exactly what I did in a local test.
