### ISSUE TITLE
Pass additional requirements to download query

### ISSUE THREAD

**Issue by BoehnkeC** [dlr-eoc/ukis-pysat#27]
The method [query_metadata](https://github.com/dlr-eoc/ukis-pysat/blob/master/ukis_pysat/data.py#L74) takes a set of arguments and fills the [sentinelsat API query](https://github.com/dlr-eoc/ukis-pysat/blob/master/ukis_pysat/data.py#L150).

Additional requirements such as the product type, e.g. GRS for Sentinel-1 data, are not accepted.

A solution would be to accept **kwargs at method call. However, kwargs is emptied several times, e.g. [here](https://github.com/dlr-eoc/ukis-pysat/blob/master/ukis_pysat/data.py#L136). This should be taken into account for the implementation of this feature.

**Comment by fwfichtner** [comment]
Like discussed, go for it.

**Comment by MWieland** [comment]
So far we decided not to support too specific query parameters to stay flexible enough across sources. When we implement additional query parameter we need to make sure that they are also supported by all sources (Scihub, EarthExplorer and Local filesystem). This is also the reason why we implemented the meta.filter() function which allows to filter the return of any query (MetadataCollection) by any metadata attribute (including product type):

`src = Source(source=Datahub.Scihub)
meta = src.query_metadata(
    platform=Platform.Sentinel2,
    date=("20200101", "NOW"),
    aoi=(11.90, 51.46, 11.94, 51.50),
    cloud_cover=(0, 50),
)

# filter MetadataCollection by producttype
meta.filter(filter_dict={"producttype": "S2MSI1C"})`

**Comment by BoehnkeC** [comment]
Yes, I already worked with the meta.filter() function. However, this applies after the query has been executed. I also think it is quite logical to have a prefilter set reducing the number of results to the requested essentials.

**Comment by fwfichtner** [comment]
I also think that this is easy to solve using `**keywords` in [Sentinelsat](https://github.com/sentinelsat/sentinelsat/blob/master/sentinelsat/sentinel.py#L124). It then depends on the user to handle this properly. If something like this does not exist for EarthExplorer we can empty them like we do now.

**Comment by BoehnkeC** [comment]
**Problem**
When implementing the **kwargs functionality into the `query_metadata` method I noticed that the additional query arguments are not part of the final meta data object. So if I'm interested in Sentinel-1 scenes in IW mode and I call 
```
query_metadata(platform=Datahub.Scihub,
               date=date,
               aoi=aoi,
               cloud_cover=None,
               sensoroperationalmode="IW"
               )
```

I get the desired results but no information about the sensor mode in the meta data object. This is natural as the meta data object is only filled with certain fields defining the data source.

**Requirement**
The additoinal (pre-filtering) attribute should be part of the final meta data. 

**Solutions**
Several options arise from this point:
1. We could blindly pass all retrieved meta data from the source API call to the meta data object.
1. We extend the meta data object with additional fields as providedin the corresponding GUI search (e.g. for Sentinel-1 also include sensor mode & polarization).
1. We define only crucial information such as acquisition time, orbit, platform etc. which are set any time as they are meant to be consistent. In a further step we define sensor specific attributes to be part of the final meta data object.

**Comments on the solutions**
These points directly refer to the numbered list above.
1.  Passing all returned argument contradicts the harmonization.
1.  This is the easiest solution. However, it is quite unsatisfying and contradicts a programatic solution.
1.  The solution I propose. This would mean to only define the very basic attributes of data sources. Any additional argument describing the sensor itself is treated separately. This implies having a list of sensors to be harmonized by ukis_pysat.

**Comment by BoehnkeC** [comment]
Although not directly related, it is worth mentioning the issue on the [metadata object](https://github.com/dlr-eoc/ukis-pysat/issues/13).

**Comment by fwfichtner** [comment]
@BoehnkeC will you finish this for 0.5.0 or shall we move it to 0.6.0?

**Comment by BoehnkeC** [comment]
Let's move this to 0.6.0.

**Comment by fwfichtner** [comment]
@BoehnkeC what you see [here](https://github.com/dlr-eoc/ukis-pysat/issues/27#issuecomment-634724348) is true, but a matter of how we define the item. Do you want to opt for extensions: https://github.com/stac-extensions/sar

**Comment by fwfichtner** [comment]
@shiwakotisurendra just expose keywords for now, we can do the extensions later.
