### ISSUE TITLE
Handle unavailable products

### ISSUE THREAD

**Issue by BoehnkeC** [dlr-eoc/ukis-pysat#28]
We do not provide any offline handling, i.e. if a product could not be reached due to network issues or if a product has been archived. 

For instance, the Copernicus SciHub moves Sentinel data to the LTA if being older than one year. Although meta data can be fetched, the data is treated as offline and requires restoration from the LTA:
`Product ee4c3e9e-c1c9-43b2-a4fd-775ba63aec7b is not online. Triggering retrieval from long term archive.`
Furthermore, the user is not allowed to send more than two or three LTA requests. Any further request will throw an HTTP error 403 and raises a SentinelAPILTAError.

If sending too many requests in a given amount of time, the sentinelsat module raises a HTTP 429 error.

The sentinelsat API offers some functionalities, e.g. checking the online status of a resource:
`self.api.get_product_odata(product_uuid)['Online']`

Error handling could be provided through:
```
except sentinelsat.SentinelAPIError as (e):
    if e.response.status_code == 403:
        logger.warning(f"Requests exceed user quota, {e}")
```

**Comment by BoehnkeC** [comment]
To clarify this: It would be nice not to end our script with an HTTP error 403 raised by senstinelsat. If the error occured we could log as follows:
`Scenes S1, S2, S3, S4, S5 were requested. The requested scene count exceeds the supported number of requests. S1, S2 and S3 are offline and LTA retrieval was triggered. S4 and S5 will be triggered when the request has been resolved.`

**Comment by fwfichtner** [comment]
How much does [`sentinelsat.download_all()`](https://github.com/sentinelsat/sentinelsat/blob/9c6269c9ec04e1d2f41ac671d75caf23077bbc25/sentinelsat/sentinel.py#L678) already cover everything you need? This should work even when we focus on single scenes for now.

**Comment by mhelleis** [comment]
as of today sentinelsat.download_all() doesn't work for me, since it triggers an [`user quota exceeded`](https://github.com/sentinelsat/sentinelsat/issues/493) error if data has to be retrieved from the LTA. Furthermore, currently there is a general problem with LTA data retrieval. [Sentinel-1 and Sentinel-2 data seems to be broken](https://github.com/sentinelsat/sentinelsat/issues/497) (i.e. the files are only a few MB in size), although this is no Sentinelsat problem but lies with Copernicus Scihub.

I'll check again when I'm back after next week and report here if anything has changed.

**Comment by fwfichtner** [comment]
Okay, that's annoying. We should monitor this and think about it again once it is fixed.

**Comment by fwfichtner** [comment]
@mhelleis you could try again with https://github.com/sentinelsat/sentinelsat/pull/532 once it has been released.

**Comment by mhelleis** [comment]
@fwfichtner will do. However, we should discuss if we should switch to using [eodag](https://github.com/CS-SI/eodag), or at least implement it as an alternative way. Even after Scihub tried to fix the LTA issues, there are missing scenes (which can be found on ONDA using eodag though). Furthermore, the LTA retrieval is much faster on ONDA.

**Comment by fwfichtner** [comment]
`eodag` can replace a lot of parts of `ukis-pysat`, so it would not make sense to include it here. You can switch to eodag in your projects though.
