### ISSUE TITLE
Image coordinate order

### ISSUE THREAD

**Issue by MWieland** [dlr-eoc/ukis-pysat#31]
We use the coordinate order of rasterio when loading images, which is channels first (channels, rows, cols). Most image processing, visualization and machine learning libraries, however, use channels last (rows, cols, channels) for image coordinate convention (e.g. scikit-image, opencv, pillow, matplotlib, etc.).  

In order to avoid confusion and to adjust to user requirements more easily it would be great if we could provide an option to change the coordinate order upon instantiation of an image object. 

I know that Rasterio provides conversion methods [here](https://rasterio.readthedocs.io/en/latest/topics/image_processing.html?highlight=read#image-processing-software), but it would be convenient if the order could be set once (e.g. as env var or parameter in Image init) to comply with a user's requirements.

Tensorflow for example provides such a switch between channels first and channels last to account for performance differences when training on GPU or CPU.

**Comment by fwfichtner** [comment]
Does that mean we would need to change order internally everytime `rasterio` is called and the order is different? Isn't explicitely calling these functions less confusing?

**Comment by MWieland** [comment]
We could for example use private attribute `__arr` internally and property arr with switch between channels_first or channels_last. Just gave it quick try and the following works without modifying any of the method routines in the rest of the class:
```python
class Image:
    def __init__(self, path=None, dataset=None, arr=None, dimorder='channels_first'):
        if path:
            if isinstance(path, str):
                self.dataset = rasterio.open(path)
                self.__arr = self.dataset.read()
            else:
                raise TypeError(f"path must be of type str")
        else:
            if isinstance(dataset, rasterio.io.DatasetReader) and isinstance(arr, np.ndarray):
                self.dataset = dataset
                self.__arr = arr
            else:
                raise TypeError(
                    f"dataset must be of type rasterio.io.DatasetReader and arr must be of type " f"numpy.ndarray"
                )
        self.dimorder = dimorder
        self.transform = self.dataset.transform
        self.crs = self.dataset.crs
        self.da_arr = None

    @property
    def arr(self):
        if self.dimorder == "channels_last":
            arr = np.moveaxis(self.__arr, 0, -1)
        else:
            arr = self.__arr
        return arr
```

**Comment by fwfichtner** [comment]
I am not sure about this, this has effect on many other methods as well. Can you clearify why you would want to have this? It seems like we add an unnecessary layer of complexity and [`rasterio.plot.reshape_as_image` ](https://github.com/mapbox/rasterio/blob/e855631fa71ef7741d112b26c967f66e3adba0da/rasterio/plot.py#L193) and `rasterio.plot.reshape_as_raster` do everything we want if I understand this correctly.

**Comment by BoehnkeC** [comment]
Rasterio calls numpy internally:
```
def reshape_as_image(arr):
    # swap the axes order from (bands, rows, columns) to (rows, columns, bands)
    im = np.ma.transpose(arr, [1, 2, 0])
```

I agree to @MWieland to incorporate this functionality as most image processing libraries have a different layer order. At this point the user would need to swap the axes manually in every script when calling ukis_pysat and we could at least provide the possibility of outsourcing this.

It would be interesting to know, if `np.moveaxis()` and `np.ma.transpose()` require equal computational resources or not.

**Comment by MWieland** [comment]
From a users perspective I would like to set the preferred dimorder once (ideally as env or similar) and then not bother about it anymore when using the package. Many people who would use this package will use one or several of the above mentioned packages that use channels_last to further analyse the images. Having a dedicated central switch for the dimorder could help to avoid nasty bugs related to forgetting to explicitly call one of the rasterio methods to reshape the raster.

If we implement it in a way similar as above (this is just a very first sketch) it would not affect any other methods that are used internally to the class. We would just upon calling Image().arr from outside the class return the array in the desired dimorder. Not sure if I miss something else here.

Btw, all the unittests pass with the above solution and with both dimorders specified.

**Comment by fwfichtner** [comment]
Okay, I didn't undestand how this works at first. 

I updated the code a little bit, still needs some work though. Please use rasterio internally as well. I wouldn't call it "channel" because others refer to it as "band".
