### ISSUE TITLE
Image write compression and dtype

### ISSUE THREAD

**Issue by MWieland** [dlr-eoc/ukis-pysat#32]
The [Image.write_to_file()](https://github.com/dlr-eoc/ukis-pysat/blob/master/ukis_pysat/raster.py#L341) method could be expanded to support optional image compression (e.g. Packbits or LZW). This is necessary to reduce the storage space for example when saving binary masks to disk. 

To achieve this we basically would have to update the profile with "compress" and optionally also "nbits" attributes. Beyond this, the "tiled" attribute could be useful to support.

Also this method defines as default dtype uint16. It would be more reasonable to set the default dtype to the dtype of the Image array in my opinion. This would allow us to stay consistent between image loading and writing.

**Comment by fwfichtner** [comment]
Good point, these options should have been in there from the beginning.
