### ISSUE TITLE
Image dataset update

### ISSUE THREAD

**Issue by MWieland** [dlr-eoc/ukis-pysat#35]
When we do a transformation on the `Image` object, the underlying rasterio `dataset` should be updated accordingly. This does not happen at the moment and may be confusing and lead to problems when chaining several transformations. For example:

```python
img = Image(path="dummy.tif")
img.mask_img().warp()
```
This would create an incorrect output, because `mask_img()` updates `transform` and `arr`, but not the entire `dataset`. `Dataset` is however used by `warp()`. At the moment `warp()` would be applied on the original `dataset` and not on the transformed one from `mask_img()`.

**Comment by fwfichtner** [comment]
It's a good point to do that because our library acts as another wrapper around `rasterio` where this is more implicit.
