### ISSUE TITLE
Dangling rasterio.dataset

### ISSUE THREAD

**Issue by fwfichtner** [dlr-eoc/ukis-pysat#45]
We don't enforce closing of the dataset, and we're not even very clear about that you should do this in the documentation (even though we offer the possibility), nor do we close `img` when we're testing.

We could offer using ukis-pysat as context manager or at least document this better and use it ourselves.

**Comment by fwfichtner** [comment]
To clearify, we're opening the dataset, but don't enforce closing (but have the option). Another alternative would be using a context manager of offering the option, like we do with the `data` class.

```python
    class Image:
        def __init__(self
             self.dataset = rasterio.open(path)

        ...

        def close(self):
            """closes Image"""
            self.dataset.close()
```

**Comment by fwfichtner** [comment]
With #47 this is at least much better for the tests.

**Comment by fwfichtner** [comment]
Let's really make it possible to wrap the whole library in a context manager.

**Comment by fwfichtner** [comment]
Let's really make it possible to wrap it all up in a context manager.

**Comment by MWieland** [comment]
Agree with that.
