### ISSUE TITLE
__update_dataset() in raster.Image() does not update dtype

### ISSUE THREAD

**Issue by MWieland** [dlr-eoc/ukis-pysat#52]
[__update_dataset()](https://github.com/dlr-eoc/ukis-pysat/blob/b249ee8210ce43034889ef0452062d117513cc92/ukis_pysat/raster.py#L153) does not update dtype. The following is a simple example that shows the problem:

```python
from ukis_pysat.raster import Image
from ukis_pysat.members import Platform


file = "D:/tmp/test/T32UPU_20200413T100549_B01.jp2"

# read image
img = Image(data=file, dimorder="last")
print(img.arr.dtype)
>> uint16

# dn2toa
# NOTE: this modifies img dtype
img.dn2toa(platform=Platform.Sentinel2)
print(img.arr.dtype)
>> float32

# subset
# BUG: this overwrite the img dtype modified by dn2toa
img.mask_image(bbox=(654700.76, 663334.23, 5324479.29, 5330987.60), crop=True, pad=False)
print(img.arr.dtype)
>> uint16
```
Suggest to make sure that [__update_dataset()](https://github.com/dlr-eoc/ukis-pysat/blob/b249ee8210ce43034889ef0452062d117513cc92/ukis_pysat/raster.py#L153) upon calling takes what it can get from the array and enforce passing crs and transform information separately (similar to what we do with creating an Image from an array, just in memory).

**Comment by fwfichtner** [comment]
Interesting, that's what `rasterio.mask.mask` returns. Does this also happen when you `pad=True`, because in your case, when the dataset is updated, the `dtype `is `uint16` again already..
