### ISSUE TITLE
Improve plotting of MetadataCollection to_pandas method

### ISSUE THREAD

**Issue by MWieland** [dlr-eoc/ukis-pysat#56]
When plotting a pandas dataframe that holds the return values of a [MetadataCollection](https://github.com/dlr-eoc/ukis-pysat/blob/96196d955f28b96249b9b00e56c24321963f0a79/ukis_pysat/data.py#L451) the columns are cut off at a fixed length. To avoid this behaviour, suggest to add `pd.set_option()`.

**Comment by BoehnkeC** [comment]
Can you share the option you want to set? Is it also possible to have the options adapted to a wide range of display geometries?

**Comment by MWieland** [comment]
The option would be related to the column width, which would result in `pd.set_option('display.max_colwidth', -1)` to adapt to different display geometries.

**Comment by BoehnkeC** [comment]
Excellent!

**Comment by MWieland** [comment]
Manually closing this issue. This has been resolved in pull request #61
