### ISSUE TITLE
Make pack and unpack methods more flexible

### ISSUE THREAD

**Issue by MWieland** [dlr-eoc/ukis-pysat#57]
In their current implementation, [unpack](https://github.com/dlr-eoc/ukis-pysat/blob/96196d955f28b96249b9b00e56c24321963f0a79/ukis_pysat/file.py#L21) and [pack](https://github.com/dlr-eoc/ukis-pysat/blob/96196d955f28b96249b9b00e56c24321963f0a79/ukis_pysat/file.py#L33) require the file format to be specified. This could be easily extracted from the file ending. Also the parameter names could use some renaming to be more self-explanatory. Suggest to modify these methods as follows:

```python
def unpack(src_file, target_dir=None):
    """Unpack an archive, does not add anything to shutil, but makes aware it exists.

    :param src_file: path to source file to be extracted including extension.
    :param target_dir: directory where the archive is unpacked. If not provided, the current working directory is used.
    """
    if target_dir:
        shutil.unpack_archive(src_file, target_dir)
    else:
        shutil.unpack_archive(src_file)


def pack(src_dir, target_file):
    """Create an archive file (such as zip or tar) from a directory.

    :param src_dir: source directory to be archived.
    :param target_file: path to target file including extension.
    """
    base = os.path.basename(target_file)
    name = base.split(".")[0]
    format = base.split(".")[1]
    archive_from = os.path.dirname(src_dir)
    archive_to = os.path.basename(src_dir.strip(os.sep))
    shutil.make_archive(name, format, archive_from, archive_to)
    shutil.move("%s.%s" % (name, format), target_file)
```

**Comment by BoehnkeC** [comment]
I noticed we are not using the current string formatting procedure in the pack method:
`shutil.move("%s.%s" % (name, format), target_file)`.

String formatting with the %-operator not technically deprecated but also not really recommened to use. I suggest switching to the [current implementation](https://docs.python.org/3/library/stdtypes.html#str.format), such as:
`shutil.move("{}.{}".format(name, format), target_file)`

**Comment by MWieland** [comment]
That is a very good suggestion. Thanks for pointing this out!

**Comment by fwfichtner** [comment]
This whole method is basically unnecessary (anyone can just use the standard library and this method does nothing else) and was only implemented as an example. So I would either keep it as it is or remove it entirely. Feel free to close if you agree.

**Comment by MWieland** [comment]
Good point. In this case I would rather remove it entirely. These methods are also not strictly related to ukis-pysat's core objectives to deal with satellite imagery. @BoehnkeC what do you think about it?

**Comment by BoehnkeC** [comment]
I agree with @fwfichtner that these methods are more or less a copy of the standard library and are not really connected to ukis-pysat as you @MWieland pointed out already.
