### ISSUE TITLE
Add local file directories as data sources

### ISSUE THREAD

**Issue by MWieland** [dlr-eoc/ukis-pysat#6]
It would be great to be able to read metadata from local file system so that we can perform tasks like: Give me all S2 scenes in directory x with less than y% cloud cover. [TinyDB](https://tinydb.readthedocs.io/en/latest/) could be a possible package to get started with.

**Comment by fwfichtner** [comment]
Please consider carefully whether we want to add another dependency. [sqlite](https://docs.python.org/3.7/library/sqlite3.html) might just do it as well.
