### ISSUE TITLE
Memory Leak in Image

### ISSUE THREAD

**Issue by MWieland** [dlr-eoc/ukis-pysat#62]
Image class has a memory leak that becomes significant when running multiple iterations or performing multiple transformations on an Image instance. The following script highlights the problem:

```python
import numpy as np
import rasterio
import psutil
from ukis_pysat.raster import Image

def main():
    crs = "EPSG:32612"
    transform = rasterio.Affine(30.0, 0.0, 358485.0, 0.0, -30.0, 4265115.0)

    for i in range(100):
        arr = np.random.randint(0, 100, size=(2000,7200,1), dtype='int16')
        with Image(data=arr, crs=crs, transform=transform, dimorder="last") as img:
            img.warp(dst_crs="EPSG:4326", resolution=0.003)
            print(img.dataset.bounds)

        mem_pct = psutil.virtual_memory().percent
        print(f'Memory used: {mem_pct}%')

if __name__ == '__main__':
    main()
```

Running this script on the current implementation of Image the memory is linearly increasing. I could narrow this down to [__update_dataset](https://github.com/dlr-eoc/ukis-pysat/blob/96196d955f28b96249b9b00e56c24321963f0a79/ukis_pysat/raster.py#L149) method, which initializes a MemoryFile as follows:

```python
        memfile = MemoryFile()
        with memfile.open(**meta) as ds:
            ds.write(self.__arr)

        return memfile.open()
```

Here the memory file is not properly closed and with each call to [__update_dataset](https://github.com/dlr-eoc/ukis-pysat/blob/96196d955f28b96249b9b00e56c24321963f0a79/ukis_pysat/raster.py#L149) we add to the memory. A possible fix for this could be:

```python
        memfile = MemoryFile()
        with memfile.open(**meta) as ds:
            ds.write(self.__arr)
        self.dataset = memfile.open()
        memfile.close()
```

Running above test script on the fixed version of [__update_dataset](https://github.com/dlr-eoc/ukis-pysat/blob/96196d955f28b96249b9b00e56c24321963f0a79/ukis_pysat/raster.py#L149)  keeps the memory consumption at a stable level.

Yet another MemoryLeak issue that adds on top of this one is related to the rasterio version. Above fix works fine on rasterio<=1.1.4. With release of rasterio 1.1.5. changes to the MemoryFile class where made that caused memory leaks. For details see the following rasterio issue: https://github.com/mapbox/rasterio/issues/1953
Solution for the time being: do not upgrade to rasterio 1.1.5.

**Comment by fwfichtner** [comment]
rasterio 1.1.6 is out and it should be [fixed](https://github.com/mapbox/rasterio/blob/master/CHANGES.txt): 

> - Clean up VSI files left by MemoryFileBase, resolving #1953
