### ISSUE TITLE
Add array setter

### ISSUE THREAD

**Issue by BoehnkeC** [dlr-eoc/ukis-pysat#67]
Instancing an Image object with `self.img = ukis_pysat.raster.Image(self.path_to_img)` gives access to attributes of the Image class, e.g. `self.img.arr`.

At some point it is desired to alter `self.img.arr`. However, `self.img.arr = self.img.arr * 10` fails with an `AttrbiuteError`.

Suggest to extend the property decorator. Current implementation is:
```
@property
def arr(self):
    """array property"""
    if self.dimorder == "first":
        return self.__arr
    else:
        return reshape_as_image(self.__arr)
```

This could be extended with:
```
@arr.setter
def arr(self, value):
    self.__arr = value
```

**Comment by MWieland** [comment]
Agree with the fact that we need to be able to set arr. This looks like a clean and straight forward solution to this.

**Comment by fwfichtner** [comment]
I guess you can add this quite easily, please add a check for value.
