### ISSUE TITLE
EarthExplorer metadata platformname incorrect.

### ISSUE THREAD

**Issue by fwfichtner** [dlr-eoc/ukis-pysat#71]
**Describe the bug**
Metadata of EarthExplorer is not returning the correct Platfromname (like it used to?). Parsing suddenly goes wrong.

**To Reproduce**
Run the test for `query_metadata`, like https://github.com/dlr-eoc/ukis-pysat/runs/950561059

**Expected behavior**
Platform name should be a part of `Platform(Enum)`.

**Additional context**
This is the reason all our tests currently fail.

**Comment by BoehnkeC** [comment]
Is it possible to have a more descriptive test? Sth. like _Platformname incorrect_?
