### ISSUE TITLE
Replace os.path with pathlib

### ISSUE THREAD

**Issue by fwfichtner** [dlr-eoc/ukis-pysat#78]
We could consider using [pathlib](https://docs.python.org/3/library/pathlib.html) instead of os.path for more readability and to be more modern.

**Comment by MWieland** [comment]
pathlib is clearly the way to go! See [here](https://treyhunner.com/2018/12/why-you-should-be-using-pathlib/) for an easy to read comparison to os.path module. So far I feel that most of us are just using os.path module out of habit.

**Comment by BoehnkeC** [comment]
> When I discovered Python’s new pathlib module a few years ago, I initially wrote it off as being a slightly more awkward and unnecessarily object-oriented version of the os.path module.

I agree to 100% with the author. However, I'm wrong. I'm quite used to `os.path` but everytime I struggle with its sub modules I would like to have something easier to use. We should go for `pathlib`.
