### ISSUE TITLE
Nodata values not available when creating dataset from array

### ISSUE THREAD

**Issue by BoehnkeC** [dlr-eoc/ukis-pysat#82]
Creating an `Image.dataset` from a numpy array produces a rasterio dataset with the following metadata:

```
meta = {
    "driver": "GTiff",
    "dtype": self.__arr.dtype,
    "nodata": nodata,
    "height": self.__arr.shape[-2],
    "width": self.__arr.shape[-1],
    "count": self.__arr.shape[0],
    "crs": crs,
    "transform": transform,
}
```

The instance `nodata` is given as an argument of the method: `__update_dataset(self, crs, transform, nodata=None)`. However, `nodata` is not handed upon function call `self.__update_dataset(crs, transform)` which leaves the new dataset with no nodata value.

Suggest to introduce a nodata value when creating datasets from arrays such as `self.__update_dataset(crs, transform, nodata=nodata)`. This requires handing the nodata value to the instantiation of the Image class `__init__(self, data, dimorder="first", crs=None, transform=None, nodata=None)` if usage is desired.

**Comment by fwfichtner** [comment]
Yes, that's a bug because it is only in the init. Fixing it makes the init less nice, but we might think of a default value here even.

Why are you not using the issue template for this? Would be easier to read.

**Comment by fwfichtner** [comment]
Setting different nodatavals per band is not supported, see https://github.com/mapbox/rasterio/issues/1859#issuecomment-577386516.
