### ISSUE TITLE
get_polarization_from_s1_filename() returns multiple types

### ISSUE THREAD

**Issue by fwfichtner** [dlr-eoc/ukis-pysat#92]
**Describe the bug**
I'm labelling this as a bug, because it is confusing to get different types and we do not actually need it as list

**To Reproduce**
Just run `get_polarization_from_s1_filename()` with dual.

**Expected behavior**
Either return a string `"POL"` or if it's dual `"POL1,POL2"`

**Additional context**
SNAP always expects a string, so there's no reason to ever make this a list.

**Comment by marceloFA** [comment]
I have a PR on this, I just have to sign the CLA to submit it. is it fine?
